### ISSUE TITLE
Keybind triggers when naming a new playlist from the "Save" button

### ISSUE THREAD

**Issue by lambdadog** [darco1991/youtube-full-windowed#4]
On the latest version released on AMO (1.0.9).

### To reproduce:

 - Click the "Save" button at the bottom right of the youtube video.
 - Click "Create new playlist"
 - Use `w` in the name of the playlist

The video is windowed-fullscreened in the background and the text box is defocused, although `w` is still entered into it. If you're not paying close attention you're liable to hit a number of native keybinds as you continue typing.

**Comment by darco1991** [comment]
FIXED
